// Auto-generated from App Store Connect pricing CSV files
// Monthly: Confirm Subscription Price?-3.csv
// Yearly: Confirm Subscription Price?-4.csv

export interface PricingInfo {
  monthly: {
    price: number;
    currency: string;
  };
  yearly: {
    price: number;
    currency: string;
  };
}

// Country code to pricing mapping
export const PRICING_DATA: Record<string, PricingInfo> = {
  AF: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  AL: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  DZ: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  AO: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  AI: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  AG: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  AR: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  AM: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  AU: { monthly: { price: 5.99, currency: 'AUD' }, yearly: { price: 39.99, currency: 'AUD' } },
  AT: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  AZ: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  BS: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 24.99, currency: 'USD' } },
  BH: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 24.99, currency: 'USD' } },
  BB: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  BY: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  BE: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  BZ: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  BJ: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  BM: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  BT: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  BO: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  BA: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  BW: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  BR: { monthly: { price: 24.9, currency: 'BRL' }, yearly: { price: 149.9, currency: 'BRL' } },
  VG: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  BN: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  BG: { monthly: { price: 8.99, currency: 'BGN' }, yearly: { price: 49.99, currency: 'BGN' } },
  BF: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  KH: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 24.99, currency: 'USD' } },
  CM: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  CA: { monthly: { price: 4.99, currency: 'CAD' }, yearly: { price: 29.99, currency: 'CAD' } },
  CV: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  KY: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  TD: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  CL: { monthly: { price: 4990, currency: 'CLP' }, yearly: { price: 24990, currency: 'CLP' } },
  CN: { monthly: { price: 28.0, currency: 'CNY' }, yearly: { price: 168.0, currency: 'CNY' } },
  CO: { monthly: { price: 19900.0, currency: 'COP' }, yearly: { price: 99900.0, currency: 'COP' } },
  CD: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  CG: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  CR: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  CI: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  HR: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  CY: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  CZ: { monthly: { price: 99.0, currency: 'CZK' }, yearly: { price: 599.0, currency: 'CZK' } },
  DK: { monthly: { price: 39.0, currency: 'DKK' }, yearly: { price: 199.0, currency: 'DKK' } },
  DM: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  DO: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  EC: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  EG: { monthly: { price: 199.99, currency: 'EGP' }, yearly: { price: 1199.99, currency: 'EGP' } },
  SV: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  EE: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  SZ: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  FJ: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  FI: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  FR: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  GA: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  GM: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  GE: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  DE: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  GH: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  GR: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  GD: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  GT: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  GW: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  GY: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  HN: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  HK: { monthly: { price: 32.0, currency: 'HKD' }, yearly: { price: 188.0, currency: 'HKD' } },
  HU: { monthly: { price: 1790, currency: 'HUF' }, yearly: { price: 9990, currency: 'HUF' } },
  IS: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  IN: { monthly: { price: 399.0, currency: 'INR' }, yearly: { price: 2299.0, currency: 'INR' } },
  ID: { monthly: { price: 69000, currency: 'IDR' }, yearly: { price: 399000, currency: 'IDR' } },
  IQ: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  IE: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  IL: { monthly: { price: 14.9, currency: 'ILS' }, yearly: { price: 79.9, currency: 'ILS' } },
  IT: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  JM: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  JP: { monthly: { price: 600, currency: 'JPY' }, yearly: { price: 3500, currency: 'JPY' } },
  JO: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  KZ: { monthly: { price: 2490.0, currency: 'KZT' }, yearly: { price: 12990.0, currency: 'KZT' } },
  KE: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  KR: { monthly: { price: 5500, currency: 'KRW' }, yearly: { price: 33000, currency: 'KRW' } },
  XK: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  KW: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  KG: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 24.99, currency: 'USD' } },
  LA: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 24.99, currency: 'USD' } },
  LV: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  LB: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  LR: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  LY: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  LT: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  LU: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  MO: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  MG: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  MW: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  MY: { monthly: { price: 19.9, currency: 'MYR' }, yearly: { price: 99.9, currency: 'MYR' } },
  MV: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  ML: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  MT: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  MR: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  MU: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  MX: { monthly: { price: 89.0, currency: 'MXN' }, yearly: { price: 499.0, currency: 'MXN' } },
  FM: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  MD: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  MN: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  ME: { monthly: { price: 3.99, currency: 'EUR' }, yearly: { price: 19.99, currency: 'EUR' } },
  MS: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  MA: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  MZ: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  MM: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  NA: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  NR: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  NP: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  NL: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  NZ: { monthly: { price: 6.99, currency: 'NZD' }, yearly: { price: 39.99, currency: 'NZD' } },
  NI: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  NE: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  NG: { monthly: { price: 6900.0, currency: 'NGN' }, yearly: { price: 39900.0, currency: 'NGN' } },
  MK: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  NO: { monthly: { price: 49.0, currency: 'NOK' }, yearly: { price: 299.0, currency: 'NOK' } },
  OM: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  PK: { monthly: { price: 1100.0, currency: 'PKR' }, yearly: { price: 5900.0, currency: 'PKR' } },
  PW: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  PA: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  PG: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  PY: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  PE: { monthly: { price: 17.9, currency: 'PEN' }, yearly: { price: 99.9, currency: 'PEN' } },
  PH: { monthly: { price: 249.0, currency: 'PHP' }, yearly: { price: 1490.0, currency: 'PHP' } },
  PL: { monthly: { price: 19.99, currency: 'PLN' }, yearly: { price: 99.99, currency: 'PLN' } },
  PT: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  QA: { monthly: { price: 14.99, currency: 'QAR' }, yearly: { price: 79.99, currency: 'QAR' } },
  RO: { monthly: { price: 19.99, currency: 'RON' }, yearly: { price: 119.99, currency: 'RON' } },
  RU: { monthly: { price: 349.0, currency: 'RUB' }, yearly: { price: 1990.0, currency: 'RUB' } },
  RW: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  ST: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  SA: { monthly: { price: 17.99, currency: 'SAR' }, yearly: { price: 99.99, currency: 'SAR' } },
  SN: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  RS: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  SC: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  SL: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  SG: { monthly: { price: 5.98, currency: 'SGD' }, yearly: { price: 34.98, currency: 'SGD' } },
  SK: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  SI: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  SB: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  ZA: { monthly: { price: 79.99, currency: 'ZAR' }, yearly: { price: 499.99, currency: 'ZAR' } },
  ES: { monthly: { price: 4.99, currency: 'EUR' }, yearly: { price: 24.99, currency: 'EUR' } },
  LK: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  KN: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  LC: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  VC: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  SR: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 24.99, currency: 'USD' } },
  SE: { monthly: { price: 49.0, currency: 'SEK' }, yearly: { price: 299.0, currency: 'SEK' } },
  CH: { monthly: { price: 3.0, currency: 'CHF' }, yearly: { price: 20.0, currency: 'CHF' } },
  TW: { monthly: { price: 120, currency: 'TWD' }, yearly: { price: 790, currency: 'TWD' } },
  TJ: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 24.99, currency: 'USD' } },
  TZ: { monthly: { price: 11900.0, currency: 'TZS' }, yearly: { price: 69900.0, currency: 'TZS' } },
  TH: { monthly: { price: 149.0, currency: 'THB' }, yearly: { price: 799.0, currency: 'THB' } },
  TO: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  TT: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  TN: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  TR: { monthly: { price: 199.99, currency: 'TRY' }, yearly: { price: 1199.99, currency: 'TRY' } },
  TM: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  TC: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  UG: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  UA: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  AE: { monthly: { price: 14.99, currency: 'AED' }, yearly: { price: 89.99, currency: 'AED' } },
  GB: { monthly: { price: 3.99, currency: 'GBP' }, yearly: { price: 22.99, currency: 'GBP' } },
  US: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 24.99, currency: 'USD' } },
  UY: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  UZ: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 24.99, currency: 'USD' } },
  VU: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  VE: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  VN: { monthly: { price: 119000, currency: 'VND' }, yearly: { price: 699000, currency: 'VND' } },
  YE: { monthly: { price: 3.99, currency: 'USD' }, yearly: { price: 22.99, currency: 'USD' } },
  ZM: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
  ZW: { monthly: { price: 4.99, currency: 'USD' }, yearly: { price: 29.99, currency: 'USD' } },
};

// Default fallback pricing
export const DEFAULT_PRICING: PricingInfo = {
  monthly: { price: 4.99, currency: 'USD' },
  yearly: { price: 24.99, currency: 'USD' },
};
